### ISSUE TITLE
single board view

### ISSUE THREAD

**Issue by wcampbell91** [wcampbell91/pinterest#20]
# User Story
When the view button on a board card is selected, the user should see a single board page displayed that shows all pins related to the selected board

# AC 
**WHEN** I click on the view button of a board card I should see a single board page displayed
**THEN** I should see each pin associated with that board displayed as cards
**AND** The pins cards should have an image, and a delete pin button
**AND** I should be able to click the image and be navigated to the related website for that pin
**THEN** I should see a back arrow below the cards that takes me back to the my boards page

# Dev Notes
* Use a buildSingleBoards function to call all of your pins into one place using async and print to the dom.
* Use a .forEach() to loop through the associated pins and print individual cards
* use an overlay div to show a hover effect and make each card clickable with this styling: 
```css
.pins-card {
  margin-top: 10px;
  background-color: $white;
  border: 0px;
  border-radius: 5px;
  opacity: 1;
}

.overlay {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
  width: 100%;
  opacity: 0;
  transition: .5s ease;
  background-color: $lightGray;
}

.pins-card:hover .overlay{
  opacity: 0.75;
  pointer-events: none;
}
```
*use a click event that hides the pins div and shows the boards div to go back
